### ISSUE TITLE
About this module

### ISSUE THREAD

**Issue by wyj0101** [linumiz/rixx#1]
Hi, I am from here, 
https://github.com/zephyrproject-rtos/zephyr/issues/78225#issue-2516277523
There are a few questions about this repository:
1. In the /modules/flashdb/CMakeLists.txt ,I saw xxx.c and this module , but not find some xxx.c file .Whether this is still in the preparatory stage?
2. I understand this repository is a flashDB_module for zephyr, but I saw the part about json parsing, Whether the two are related?

I don't know much about flashDB, I just want to run the database on zephyr, Please understand some wrong remarks.
In addition, Is it possible to add some notes to the repository and contribute together.

**Comment by parthitce** [comment]
> 
>     1. In the /modules/flashdb/CMakeLists.txt ,I saw xxx.c and this module , but not find some xxx.c file .Whether this is still in the preparatory stage?

flashDB itself functional and can be used independently. This is possible because we have https://github.com/armink/FlashDB/commit/523fd2052d13baf72fd1d8e177c2a162a03392be merged in the original repo.

> 
>     2. I understand this repository is a flashDB_module for zephyr, but I saw the part about json parsing, Whether the two are related?

json-c is another module which we have sample as well. But there are set of samples created for flashDB as well. @karthi012 can push it here in this repo after cleaning.

> 
> I don't know much about flashDB, I just want to run the database on zephyr, Please understand some wrong remarks. In addition, Is it possible to add some notes to the repository and contribute together.

All you need is a sample application using the flashDB API.

**Comment by wyj0101** [comment]
OK, Thanks for the answer.

**Comment by karthi012** [comment]
@wyj0101 Added sample for flashdb. It is same as sample application from the FlashDB. Make slight modifications for zephyr.
FlashDB sample is compiled and tested in nrf52840dk, sample uses the external qpsi nor flash from nrf52840dk for database storage.Please have a look.

**Comment by wyj0101** [comment]
> @wyj0101 Added sample for flashdb. It is same as sample application from the FlashDB. Make slight modifications for zephyr. FlashDB sample is compiled and tested in nrf52840dk, sample uses the external qpsi nor flash from nrf52840dk for database storage.Please have a look.

OK，Thank you！
